fund:
  coinsengine:
    enabled: false
    currency: 'tokens'
  symbol: '|'
  symbol_amount: 40
  color_of_achieved: '&a'
  color_of_remaining: '&7'
  amount_of_or_greater_than_to_announce: 5000000
  messages:
    fund:
      - '&8&l(&a&l!&8&l) Name: %name%'
      - '&8&l(&a&l!&8&l) Progress: [%symbol%] [%percent%]'
      - '&8&l(&a&l!&8&l) &7Use &c/fund help &7for help.'
    help:
      - 'Help'
    fundtop:
      header:
        - 'Fund Top:'
      playerformat: '%place%: %player%'
      footer:
        - 'It''s a footer'
    others:
      fund_reset: '&8&l(&a&l!&8&l) &cFund &7has been reset!'
      resetting_fund: '&8&l(&c&l!&8&l) &7Use &c/fund reset confirm&7!'
      not_confirming_anything: '&8&l(&c&l!&8&l) &7Use &c/fund reset&7 first!'
      no_perms: '&8&l(&c&l!&8&l) &7You don''t have permission to use the &c/fund reset &7command!'
      not_enough_money: '&8&l(&c&l!&8&l) &7You don''t have enough money!'
      all_funds_completed: '&8&l(&a&l!&8&l) &aAll funds are completed!'
      paid: '&8&l(&a&l!&8&l) &aYou have paid $%amount% to %name%!'
    broadcast:
      message_when_funded_alot: '&8&l(&a&l!&8&l) &a%player% funded $%amount% to %name%!'
      fund_finished: '&8&l(&a&l!&8&l) &a%fund% has been completed! Next fund: %next_fund%'
  goals:
    1:
      name: 'Rank Kit Gear'
      current: 0
      max: 10000000
      console_commands:
        - 'say command here'
    2:
      name: 'Kit Keys'
      current: 0
      max: 25000000
      console_commands:
        - 'say command here'
    3:
      name: 'Events'
      current: 0
      max: 50000000
      console_commands:
        - 'say command here'
    4:
      name: 'Envoys'
      current: 0
      max: 75000000
      console_commands:
        - 'say command here'
